version: '3.8'
# Contenedores configuración
services:
  mono-map:
    build: .
    #image: daniel978/mono-map-api:latest
    container_name: mono-map
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: ${MONGO_URL_DOCKER}
      PORT: 3000
      MAIL_SECRET_KEY: ${MAIL_SECRET_KEY}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAIL_USER: ${MAIL_USER}
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
    depends_on:  # Corrección aquí
      - mongo

  mongo:
    image: mongo
    container_name: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: